import { NextResponse } from "next/server";
import type { NormalizedReview } from "@/types/review";

// Generate comprehensive demo data for analytics
export async function GET() {
    try {
        const demoReviews: NormalizedReview[] = [
            // Shoreditch Heights Reviews - James Wilson review (REJECTED)
            {
                id: 1,
                type: "guest-to-host",
                status: "rejected",
                overallRating: 4.8,
                review: "Absolutely fantastic stay! The apartment was spotless and the location couldn't be better. Walking distance to everything in Shoreditch. The host was incredibly responsive and helpful. Will definitely stay again!",
                categories: {
                    cleanliness: 5.0,
                    communication: 4.8,
                    location: 5.0,
                    checkin: 4.5,
                    accuracy: 4.8,
                    value: 4.6,
                },
                submittedAt: new Date("2024-01-15"),
                guestName: "James Wilson",
                listingName: "2B N1 A - 29 Shoreditch Heights",
                channel: "hostaway",
                isApproved: false,
            },
            {
                id: 2,
                type: "guest-to-host",
                status: "published",
                overallRating: 4.3,
                review: "Great location in the heart of Shoreditch! The apartment is modern and well-equipped. Loved the industrial design and the proximity to all the trendy bars and restaurants.",
                categories: {
                    cleanliness: 4.4,
                    communication: 4.2,
                    location: 4.7,
                    checkin: 4.3,
                    accuracy: 4.4,
                    value: 4.2,
                },
                submittedAt: new Date("2025-08-28"),
                guestName: "Emma Thompson",
                listingName: "2B N1 A - 29 Shoreditch Heights",
                channel: "airbnb",
                isApproved: true,
            },
            // Canary Wharf Tower Reviews
            {
                id: 3,
                type: "guest-to-host",
                status: "published",
                overallRating: 4.8,
                review: "Perfect apartment for our London trip! Modern, clean, and stylish. The kitchen was fully equipped and the bed was super comfortable. Great communication from the host. Highly recommended!",
                categories: {
                    cleanliness: 4.9,
                    communication: 4.8,
                    location: 4.6,
                    checkin: 4.7,
                    accuracy: 4.8,
                    value: 4.6,
                },
                submittedAt: new Date("2025-09-10"),
                guestName: "Sarah Chen",
                listingName: "1B E1 B - 15 Canary Wharf Tower",
                channel: "airbnb",
                isApproved: true,
            },
            {
                id: 4,
                type: "guest-to-host",
                status: "published",
                overallRating: 4.5,
                review: "Amazing views from the 15th floor! Professional building with excellent amenities. Perfect for business travelers. The tube connections are fantastic.",
                categories: {
                    cleanliness: 4.6,
                    communication: 4.4,
                    location: 4.7,
                    checkin: 4.4,
                    accuracy: 4.5,
                    value: 4.3,
                },
                submittedAt: new Date("2025-08-22"),
                guestName: "David Kumar",
                listingName: "1B E1 B - 15 Canary Wharf Tower",
                channel: "booking",
                isApproved: true,
            },
            // Fitzrovia Square Reviews
            {
                id: 5,
                type: "guest-to-host",
                status: "published",
                overallRating: 4.4,
                review: "Outstanding! This is exactly what you want from a London stay. The apartment exceeded all expectations - beautifully designed, immaculately clean, and the location is unbeatable.",
                categories: {
                    cleanliness: 4.5,
                    communication: 4.4,
                    location: 4.7,
                    checkin: 4.3,
                    accuracy: 4.5,
                    value: 4.3,
                },
                submittedAt: new Date("2025-08-28"),
                guestName: "Elena Rodriguez",
                listingName: "Studio W1 C - 42 Fitzrovia Square",
                channel: "google",
                isApproved: true,
            },
            {
                id: 6,
                type: "guest-to-host",
                status: "published",
                overallRating: 4.6,
                review: "Perfect studio in Fitzrovia! Compact but very well designed with everything you need. The location is fantastic - walking distance to Oxford Street and the British Museum.",
                categories: {
                    cleanliness: 4.6,
                    communication: 4.5,
                    location: 4.7,
                    checkin: 4.5,
                    accuracy: 4.6,
                    value: 4.4,
                },
                submittedAt: new Date("2025-09-01"),
                guestName: "Marcus Johnson",
                listingName: "Studio W1 C - 42 Fitzrovia Square",
                channel: "airbnb",
                isApproved: true,
            },
            // Chelsea Garden Mews Reviews
            {
                id: 7,
                type: "guest-to-host",
                status: "published",
                overallRating: 4.7,
                review: "Absolutely stunning 3-bedroom in Chelsea! The garden mews setting is so charming and peaceful. Perfect for families or groups. The host thought of everything - from welcome treats to detailed local recommendations.",
                categories: {
                    cleanliness: 4.8,
                    communication: 4.6,
                    location: 4.6,
                    checkin: 4.7,
                    accuracy: 4.7,
                    value: 4.5,
                },
                submittedAt: new Date("2025-08-15"),
                guestName: "Isabella Cooper",
                listingName: "3B SW3 A - 12 Chelsea Garden Mews",
                channel: "hostaway",
                isApproved: true,
            },
            {
                id: 8,
                type: "guest-to-host",
                status: "published",
                overallRating: 4.3,
                review: "Beautiful property in an exclusive area of Chelsea. The three bedrooms are spacious and the private garden is a real bonus. Great for a luxury London experience.",
                categories: {
                    cleanliness: 4.4,
                    communication: 4.3,
                    location: 4.5,
                    checkin: 4.2,
                    accuracy: 4.4,
                    value: 4.2,
                },
                submittedAt: new Date("2025-07-28"),
                guestName: "Thomas Anderson",
                listingName: "3B SW3 A - 12 Chelsea Garden Mews",
                channel: "booking",
                isApproved: true,
            },
            // Paddington Central Reviews
            {
                id: 9,
                type: "guest-to-host",
                status: "published",
                overallRating: 4.2,
                review: "Great location near Paddington Station! Perfect for travelers arriving by train. The apartment is modern and comfortable with good amenities. Easy access to the tube network.",
                categories: {
                    cleanliness: 4.3,
                    communication: 4.2,
                    location: 4.6,
                    checkin: 4.1,
                    accuracy: 4.3,
                    value: 4.4,
                },
                submittedAt: new Date("2025-08-10"),
                guestName: "Rachel Green",
                listingName: "2B W2 D - 8 Paddington Central",
                channel: "airbnb",
                isApproved: true,
            },
            {
                id: 10,
                type: "guest-to-host",
                status: "published",
                overallRating: 4.1,
                review: "Good apartment overall. Location is excellent for transport links and the space is well-designed. Only minor issue was the WiFi was a bit slow, but everything else was great. Would stay again.",
                categories: {
                    cleanliness: 4.3,
                    communication: 3.9,
                    location: 4.5,
                    checkin: 4.1,
                    accuracy: 4.0,
                    value: 4.0,
                },
                submittedAt: new Date("2025-08-15"),
                guestName: "Michael Brown",
                listingName: "2B W2 D - 8 Paddington Central",
                channel: "hostaway",
                isApproved: true,
            },
            // Additional Shoreditch Heights Review
            {
                id: 11,
                type: "guest-to-host",
                status: "published",
                overallRating: 4.2,
                review: "Lovely stay in Shoreditch! The apartment is stylish and comfortable. Great restaurants and bars within walking distance. The shower pressure could be better, but overall very satisfied.",
                categories: {
                    cleanliness: 4.3,
                    communication: 4.3,
                    location: 4.4,
                    checkin: 4.2,
                    accuracy: 4.1,
                    value: 4.2,
                },
                submittedAt: new Date("2025-07-22"),
                guestName: "Anna Kowalski",
                listingName: "2B N1 A - 29 Shoreditch Heights",
                channel: "airbnb",
                isApproved: true,
            },
            // Lower-rated reviews for diversity
            {
                id: 12,
                type: "guest-to-host",
                status: "published",
                overallRating: 3.6,
                review: "Decent place but had some issues. The heating took a while to work properly and there was construction noise during the day. Location is great though and the apartment is nicely furnished.",
                categories: {
                    cleanliness: 3.9,
                    communication: 3.3,
                    location: 4.3,
                    checkin: 3.6,
                    accuracy: 3.5,
                    value: 3.5,
                },
                submittedAt: new Date("2025-07-08"),
                guestName: "Thomas Mueller",
                listingName: "Studio W1 C - 42 Fitzrovia Square",
                channel: "hostaway",
                isApproved: true,
            },
            {
                id: 7,
                type: "guest-to-host",
                status: "published",
                overallRating: 3.9,
                review: "Nice apartment with good amenities. The location is convenient for business trips. A few minor maintenance issues but nothing major. Host was responsive to queries.",
                categories: {
                    cleanliness: 4.0,
                    communication: 3.9,
                    location: 4.1,
                    checkin: 3.8,
                    accuracy: 3.8,
                    value: 3.9,
                },
                submittedAt: new Date("2025-06-25"),
                guestName: "David Kim",
                listingName: "1B E1 B - 15 Canary Wharf Tower",
                channel: "google",
                isApproved: true,
            },
            // Lower-rated reviews for diversity
            {
                id: 8,
                type: "guest-to-host",
                status: "published",
                overallRating: 3.3,
                review: "The apartment was okay but not what I expected from the photos. Some cleanliness issues and the internet connection was unreliable. The location saved it from being worse.",
                categories: {
                    cleanliness: 2.9,
                    communication: 3.1,
                    location: 4.0,
                    checkin: 3.4,
                    accuracy: 2.8,
                    value: 3.1,
                },
                submittedAt: new Date("2025-04-15"),
                guestName: "Lisa Thompson",
                listingName: "Studio W1 C - 42 Fitzrovia Square",
                channel: "airbnb",
                isApproved: true,
            },
            // Recent reviews for trends
            {
                id: 9,
                type: "guest-to-host",
                status: "published",
                overallRating: 4.5,
                review: "Excellent stay with top-notch amenities. The apartment is modern and well-maintained. Perfect for a couple's getaway in London. Host communication was prompt and helpful.",
                categories: {
                    cleanliness: 4.6,
                    communication: 4.4,
                    location: 4.4,
                    checkin: 4.5,
                    accuracy: 4.5,
                    value: 4.3,
                },
                submittedAt: new Date("2025-09-12"),
                guestName: "Robert Garcia",
                listingName: "3B SW3 A - 12 Chelsea Garden Mews",
                channel: "hostaway",
                isApproved: true,
            },
            {
                id: 10,
                type: "guest-to-host",
                status: "published",
                overallRating: 4.2,
                review: "Great location and comfortable apartment. Everything was as described. Minor issue with the air conditioning but the host fixed it quickly. Would recommend!",
                categories: {
                    cleanliness: 4.3,
                    communication: 4.4,
                    location: 4.4,
                    checkin: 4.0,
                    accuracy: 4.1,
                    value: 4.1,
                },
                submittedAt: new Date("2025-09-08"),
                guestName: "Maria Fernandez",
                listingName: "2B W2 D - 8 Paddington Central",
                channel: "google",
                isApproved: true,
            },
            // Additional reviews for better analytics
            {
                id: 11,
                type: "guest-to-host",
                status: "published",
                overallRating: 4.5,
                review: "Fantastic experience! The apartment is beautifully decorated and has everything you need. The host went above and beyond to make our stay comfortable.",
                categories: {
                    cleanliness: 4.7,
                    communication: 4.6,
                    location: 4.4,
                    checkin: 4.5,
                    accuracy: 4.6,
                    value: 4.5,
                },
                submittedAt: new Date("2025-08-02"),
                guestName: "Jennifer Lewis",
                listingName: "2B N1 A - 29 Shoreditch Heights",
                channel: "airbnb",
                isApproved: true,
            },
            {
                id: 12,
                type: "guest-to-host",
                status: "published",
                overallRating: 3.8,
                review: "Good value for money. The apartment is clean and functional. Location is convenient for exploring London. Some wear and tear but nothing that affected our stay significantly.",
                categories: {
                    cleanliness: 3.9,
                    communication: 3.8,
                    location: 4.1,
                    checkin: 3.7,
                    accuracy: 3.8,
                    value: 4.0,
                },
                submittedAt: new Date("2025-07-18"),
                guestName: "Mark Wilson",
                listingName: "Studio W1 C - 42 Fitzrovia Square",
                channel: "hostaway",
                isApproved: true,
            },
            // Pending reviews for analytics
            {
                id: 13,
                type: "guest-to-host",
                status: "pending",
                overallRating: 4.4,
                review: "Beautiful apartment with excellent facilities. The host was very accommodating and the check-in process was smooth. Highly recommend for business travelers.",
                categories: {
                    cleanliness: 4.5,
                    communication: 4.3,
                    location: 4.3,
                    checkin: 4.4,
                    accuracy: 4.4,
                    value: 4.2,
                },
                submittedAt: new Date("2025-09-13"),
                guestName: "Alex Morgan",
                listingName: "1B E1 B - 15 Canary Wharf Tower",
                channel: "google",
                isApproved: false,
            },
            {
                id: 14,
                type: "guest-to-host",
                status: "pending",
                overallRating: 4.1,
                review: "Nice stay overall. The apartment has a great view and is well-equipped. Just a few minor issues with the heating that were resolved quickly.",
                categories: {
                    cleanliness: 4.2,
                    communication: 4.0,
                    location: 4.3,
                    checkin: 4.1,
                    accuracy: 4.1,
                    value: 4.0,
                },
                submittedAt: new Date("2025-09-11"),
                guestName: "Sophie Anderson",
                listingName: "3B SW3 A - 12 Chelsea Garden Mews",
                channel: "airbnb",
                isApproved: false,
            },
            // Test rejected review - should NOT appear in PublicReviewsSection
            {
                id: 99,
                type: "guest-to-host",
                status: "rejected",
                overallRating: 4.2,
                review: "This review was rejected due to inappropriate content. It should not appear in the public reviews section.",
                categories: {
                    cleanliness: 4.0,
                    communication: 4.0,
                    location: 5.0,
                    checkin: 4.0,
                    accuracy: 4.0,
                    value: 4.0,
                },
                submittedAt: new Date("2025-09-10"),
                guestName: "Test Rejected User",
                listingName: "1B W1 A - 15 Test Property",
                channel: "booking",
                isApproved: false,
            },
        ];

        return NextResponse.json({
            success: true,
            data: demoReviews,
            count: demoReviews.length,
            message: "Demo review data for analytics testing",
        });
    } catch (error) {
        console.error("Error generating demo data:", error);
        return NextResponse.json(
            {
                success: false,
                error: "Failed to generate demo data",
                message:
                    error instanceof Error ? error.message : "Unknown error",
            },
            { status: 500 }
        );
    }
}
