import { NextResponse } from "next/server";
import type { NormalizedReview } from "@/types/review";

// Generate comprehensive demo data for analytics
export async function GET() {
    try {
        const demoReviews: NormalizedReview[] = [
            // High-rated reviews
            {
                id: 1,
                type: "guest-to-host",
                status: "published",
                overallRating: 9.2,
                review: "Absolutely fantastic stay! The apartment was spotless and the location couldn't be better. Walking distance to everything in Shoreditch. The host was incredibly responsive and helpful. Will definitely stay again!",
                categories: {
                    cleanliness: 9.5,
                    communication: 9.0,
                    location: 9.8,
                    checkin: 8.8,
                    accuracy: 9.2,
                    value: 8.9,
                },
                submittedAt: new Date("2025-09-05"),
                guestName: "James Wilson",
                listingName: "2B N1 A - 29 Shoreditch Heights",
                channel: "hostaway",
                isApproved: true,
            },
            {
                id: 2,
                type: "guest-to-host",
                status: "published",
                overallRating: 9.5,
                review: "Perfect apartment for our London trip! Modern, clean, and stylish. The kitchen was fully equipped and the bed was super comfortable. Great communication from the host. Highly recommended!",
                categories: {
                    cleanliness: 9.8,
                    communication: 9.5,
                    location: 9.2,
                    checkin: 9.4,
                    accuracy: 9.6,
                    value: 9.1,
                },
                submittedAt: new Date("2025-09-10"),
                guestName: "Sarah Chen",
                listingName: "1B E1 B - 15 Canary Wharf Tower",
                channel: "airbnb",
                isApproved: true,
            },
            {
                id: 3,
                type: "guest-to-host",
                status: "published",
                overallRating: 8.8,
                review: "Outstanding! This is exactly what you want from a London stay. The apartment exceeded all expectations - beautifully designed, immaculately clean, and the location is unbeatable.",
                categories: {
                    cleanliness: 9.0,
                    communication: 8.8,
                    location: 9.3,
                    checkin: 8.5,
                    accuracy: 8.9,
                    value: 8.6,
                },
                submittedAt: new Date("2025-08-28"),
                guestName: "Elena Rodriguez",
                listingName: "Studio W1 C - 42 Fitzrovia Square",
                channel: "google",
                isApproved: true,
            },
            // Good reviews
            {
                id: 4,
                type: "guest-to-host",
                status: "published",
                overallRating: 8.1,
                review: "Good apartment overall. Location is excellent and the space is well-designed. Only minor issue was the WiFi was a bit slow, but everything else was great. Would stay again.",
                categories: {
                    cleanliness: 8.5,
                    communication: 7.8,
                    location: 9.0,
                    checkin: 8.2,
                    accuracy: 8.0,
                    value: 7.9,
                },
                submittedAt: new Date("2025-08-15"),
                guestName: "Michael Brown",
                listingName: "2B N1 A - 29 Shoreditch Heights",
                channel: "hostaway",
                isApproved: true,
            },
            {
                id: 5,
                type: "guest-to-host",
                status: "published",
                overallRating: 8.4,
                review: "Lovely stay in Shoreditch! The apartment is stylish and comfortable. Great restaurants and bars within walking distance. The shower pressure could be better, but overall very satisfied.",
                categories: {
                    cleanliness: 8.6,
                    communication: 8.5,
                    location: 8.8,
                    checkin: 8.3,
                    accuracy: 8.2,
                    value: 8.3,
                },
                submittedAt: new Date("2025-07-22"),
                guestName: "Anna Kowalski",
                listingName: "3B SW3 A - 12 Chelsea Garden Mews",
                channel: "airbnb",
                isApproved: true,
            },
            // Average reviews
            {
                id: 6,
                type: "guest-to-host",
                status: "published",
                overallRating: 7.2,
                review: "Decent place but had some issues. The heating took a while to work properly and there was construction noise during the day. Location is great though and the apartment is nicely furnished.",
                categories: {
                    cleanliness: 7.8,
                    communication: 6.5,
                    location: 8.5,
                    checkin: 7.1,
                    accuracy: 6.9,
                    value: 7.0,
                },
                submittedAt: new Date("2025-07-08"),
                guestName: "Thomas Mueller",
                listingName: "2B W2 D - 8 Paddington Central",
                channel: "hostaway",
                isApproved: true,
            },
            {
                id: 7,
                type: "guest-to-host",
                status: "published",
                overallRating: 7.8,
                review: "Nice apartment with good amenities. The location is convenient for business trips. A few minor maintenance issues but nothing major. Host was responsive to queries.",
                categories: {
                    cleanliness: 8.0,
                    communication: 7.8,
                    location: 8.2,
                    checkin: 7.5,
                    accuracy: 7.6,
                    value: 7.7,
                },
                submittedAt: new Date("2025-06-25"),
                guestName: "David Kim",
                listingName: "1B E1 B - 15 Canary Wharf Tower",
                channel: "google",
                isApproved: true,
            },
            // Lower-rated reviews for diversity
            {
                id: 8,
                type: "guest-to-host",
                status: "published",
                overallRating: 6.5,
                review: "The apartment was okay but not what I expected from the photos. Some cleanliness issues and the internet connection was unreliable. The location saved it from being worse.",
                categories: {
                    cleanliness: 5.8,
                    communication: 6.2,
                    location: 8.0,
                    checkin: 6.8,
                    accuracy: 5.5,
                    value: 6.2,
                },
                submittedAt: new Date("2025-04-15"),
                guestName: "Lisa Thompson",
                listingName: "Studio W1 C - 42 Fitzrovia Square",
                channel: "airbnb",
                isApproved: true,
            },
            // Recent reviews for trends
            {
                id: 9,
                type: "guest-to-host",
                status: "published",
                overallRating: 8.9,
                review: "Excellent stay with top-notch amenities. The apartment is modern and well-maintained. Perfect for a couple's getaway in London. Host communication was prompt and helpful.",
                categories: {
                    cleanliness: 9.2,
                    communication: 8.8,
                    location: 8.7,
                    checkin: 8.9,
                    accuracy: 9.0,
                    value: 8.6,
                },
                submittedAt: new Date("2025-09-12"),
                guestName: "Robert Garcia",
                listingName: "3B SW3 A - 12 Chelsea Garden Mews",
                channel: "hostaway",
                isApproved: true,
            },
            {
                id: 10,
                type: "guest-to-host",
                status: "published",
                overallRating: 8.3,
                review: "Great location and comfortable apartment. Everything was as described. Minor issue with the air conditioning but the host fixed it quickly. Would recommend!",
                categories: {
                    cleanliness: 8.5,
                    communication: 8.7,
                    location: 8.8,
                    checkin: 8.0,
                    accuracy: 8.2,
                    value: 8.1,
                },
                submittedAt: new Date("2025-09-08"),
                guestName: "Maria Fernandez",
                listingName: "2B W2 D - 8 Paddington Central",
                channel: "google",
                isApproved: true,
            },
            // Additional reviews for better analytics
            {
                id: 11,
                type: "guest-to-host",
                status: "published",
                overallRating: 9.0,
                review: "Fantastic experience! The apartment is beautifully decorated and has everything you need. The host went above and beyond to make our stay comfortable.",
                categories: {
                    cleanliness: 9.3,
                    communication: 9.1,
                    location: 8.8,
                    checkin: 9.0,
                    accuracy: 9.2,
                    value: 8.9,
                },
                submittedAt: new Date("2025-08-02"),
                guestName: "Jennifer Lewis",
                listingName: "2B N1 A - 29 Shoreditch Heights",
                channel: "airbnb",
                isApproved: true,
            },
            {
                id: 12,
                type: "guest-to-host",
                status: "published",
                overallRating: 7.6,
                review: "Good value for money. The apartment is clean and functional. Location is convenient for exploring London. Some wear and tear but nothing that affected our stay significantly.",
                categories: {
                    cleanliness: 7.8,
                    communication: 7.5,
                    location: 8.2,
                    checkin: 7.4,
                    accuracy: 7.6,
                    value: 8.0,
                },
                submittedAt: new Date("2025-07-18"),
                guestName: "Mark Wilson",
                listingName: "Studio W1 C - 42 Fitzrovia Square",
                channel: "hostaway",
                isApproved: true,
            },
            // Pending reviews for analytics
            {
                id: 13,
                type: "guest-to-host",
                status: "pending",
                overallRating: 8.7,
                review: "Beautiful apartment with excellent facilities. The host was very accommodating and the check-in process was smooth. Highly recommend for business travelers.",
                categories: {
                    cleanliness: 8.9,
                    communication: 8.6,
                    location: 8.5,
                    checkin: 8.8,
                    accuracy: 8.7,
                    value: 8.4,
                },
                submittedAt: new Date("2025-09-13"),
                guestName: "Alex Morgan",
                listingName: "1B E1 B - 15 Canary Wharf Tower",
                channel: "google",
                isApproved: false,
            },
            {
                id: 14,
                type: "guest-to-host",
                status: "pending",
                overallRating: 8.2,
                review: "Nice stay overall. The apartment has a great view and is well-equipped. Just a few minor issues with the heating that were resolved quickly.",
                categories: {
                    cleanliness: 8.4,
                    communication: 8.0,
                    location: 8.6,
                    checkin: 8.1,
                    accuracy: 8.2,
                    value: 7.9,
                },
                submittedAt: new Date("2025-09-11"),
                guestName: "Sophie Anderson",
                listingName: "3B SW3 A - 12 Chelsea Garden Mews",
                channel: "airbnb",
                isApproved: false,
            },
        ];

        return NextResponse.json({
            success: true,
            data: demoReviews,
            count: demoReviews.length,
            message: "Demo review data for analytics testing",
        });
    } catch (error) {
        console.error("Error generating demo data:", error);
        return NextResponse.json(
            {
                success: false,
                error: "Failed to generate demo data",
                message:
                    error instanceof Error ? error.message : "Unknown error",
            },
            { status: 500 }
        );
    }
}
